[project]
name = "mm-eth"
version = "0.7.2"
description = ""
requires-python = ">=3.13"
dependencies = [
    "mm-web3~=0.5.4",
    "web3~=7.14.0",
    "typer~=0.20.0",
]
[project.scripts]
mm-eth = "mm_eth.cli.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest~=8.4.2",
    "pytest-asyncio~=1.2.0",
    "pytest-xdist~=3.8.0",
    "ruff~=0.14.2",
    "pip-audit~=2.9.0",
    "bandit~=1.8.6",
    "mypy~=1.18.2",
    "pre-commit~=4.3.0",
    "python-dotenv~=1.2.1",
]

[tool.mypy]
python_version = "3.13"
mypy_path = "stubs"
warn_no_return = false
implicit_reexport = true
strict = true
enable_error_code = ["truthy-bool", "possibly-undefined"]
exclude = ["^tests/", "^tmp/"]
[[tool.mypy.overrides]]
module = ["rlp", "rlp.sedes", "ens.utils", "ens"]
ignore_missing_imports = true

[tool.ruff]
line-length = 130
target-version = "py313"
[tool.ruff.lint]
select = ["ALL"]
# fixable = ["F401"]
ignore = [
    "TC", # flake8-type-checking, TYPE_CHECKING is dangerous, for example it doesn't work with pydantic
    "A005", # flake8-builtins: stdlib-module-shadowing
    "ERA001", # eradicate: commented-out-code
    "PT", # flake8-pytest-style
    "D", # pydocstyle
    "FIX", # flake8-fixme
    "PLR0911", # pylint: too-many-return-statements
    "PLR0912", # pylint: too-many-branches
    "PLR0913", # pylint: too-many-arguments
    "PLR2004", # pylint: magic-value-comparison
    "PLC0414", # pylint: useless-import-alias
    "FBT", # flake8-boolean-trap
    "EM", # flake8-errmsg
    "TRY003", # tryceratops: raise-vanilla-args
    "C901", # mccabe: complex-structure,
    "BLE001", # flake8-blind-except
    "S311", # bandit: suspicious-non-cryptographic-random-usage
    "TD002", # flake8-todos: missing-todo-author
    "TD003", # flake8-todos: missing-todo-link
    "RET503", # flake8-return: implicit-return
    "COM812", # it's used in ruff formatter
    "ASYNC109", # flake8-async: async-function-with-timeout
    "G004",
]
[tool.ruff.lint.pep8-naming]
classmethod-decorators = ["field_validator"]
[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["ANN", "S"]
[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B311"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
